name: Just estimation notebooks

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    # Set up
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        
        sudo apt-get install pandoc
        pip install wheel numpy # For RAIL
        pip install jupyter nbconvert # For notebooks
        
        git clone https://github.com/LSSTDESC/rail.git
        cd rail
        #pip install .[dev]
        conda install --file conda-reqs.txt
        pip install .
        rail dev install --package-file rail_packages.yml
        
    # Render estimation notebooks
    - run: python render_notebooks.py estimation
      if: always()
      
    # Commit changes
    - uses: stefanzweifel/git-auto-commit-action@v7
      if: always()
