# This workflow can be triggered manually; it also runs every Monday at 11:45 UTC.
# This workflow grabs globbed notebooks from the RAIL repository, runs them, and
# renders the notebooks with outputs into .rst files for easy integration into
# ReadTheDocs.
        
name: Render notebooks

on:
  workflow_dispatch:
  schedule:
    - cron: 45 11 * * 1

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    # Set up and installation
    - uses: actions/checkout@v6
    - name: Set up Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    - name: System deps (MPI + build)
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        build-essential libbz2-dev \
        openmpi-bin libopenmpi-dev
    - name: Install dependencies
      run: |
        cd ..
        git clone https://github.com/LSSTDESC/rail.git
        cd rail

        # The following was copied from rail's CI (from main repo) on Jan 20, 2026:
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install "numpy<2" cython
        python -m pip install --upgrade --no-binary=mpi4py mpi4py
        python -m pip install --no-build-isolation somoclu
        python -m pip install --upgrade pip
        pip install wheel numpy
        pip install .[dev]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        # Extras, for notebooks:
        pip install jupyter nbconvert # For notebooks
        sudo apt-get install pandoc
        
        
    # Render interactive notebooks
    - name: Render core notebooks
      run: |
        mkdir -p logs
        python src/rail_notebooks/render_notebooks.py core interactive_examples -v > logs/interactive_examples/core_logs.out 2>&1  | tee logs/interactive_examples/core_logs.out
      if: always()
    - name: Render creation notebooks
      run: |
        mkdir -p logs
        python src/rail_notebooks/render_notebooks.py creation interactive_examples -v > logs/interactive_examples/creation_logs.out 2>&1 | tee logs/interactive_examples/creation_logs.out
      if: always()
    - name: Render estimation notebooks
      run: |
        mkdir -p logs
        python src/rail_notebooks/render_notebooks.py estimation interactive_examples -v > logs/interactive_examples/estimation_logs.out 2>&1 | tee logs/interactive_examples/estimation_logs.out
      if: always()
    - name: Render evaluation notebooks
      run: |
        mkdir -p logs
        python src/rail_notebooks/render_notebooks.py evaluation interactive_examples -v > logs/interactive_examples/evaluation_logs.out 2>&1 | tee logs/interactive_examples/evaluation_logs.out
      if: always()
    - name: Render goldenspike notebooks
      run: |
        mkdir -p logs
        python src/rail_notebooks/render_notebooks.py goldenspike interactive_examples -v > logs/interactive_examples/goldenspike_logs.out 2>&1 | tee logs/interactive_examples/goldenspike_logs.out
      if: always()

    # Render pipeline notebooks
    - name: Render core notebooks
      run: |
        mkdir -p logs
        python src/rail_notebooks/render_notebooks.py core pipeline_examples -v > logs/pipeline_examples/core_logs.out 2>&1  | tee logs/pipeline_examples/core_logs.out
      if: always()
    - name: Render creation notebooks
      run: |
        mkdir -p logs
        python src/rail_notebooks/render_notebooks.py creation pipeline_examples -v > logs/pipeline_examples/creation_logs.out 2>&1 | tee logs/pipeline_examples/creation_logs.out
      if: always()
    - name: Render estimation notebooks
      run: |
        mkdir -p logs
        python src/rail_notebooks/render_notebooks.py estimation pipeline_examples -v > logs/pipeline_examples/estimation_logs.out 2>&1 | tee logs/pipeline_examples/estimation_logs.out
      if: always()
    - name: Render evaluation notebooks
      run: |
        mkdir -p logs
        python src/rail_notebooks/render_notebooks.py evaluation pipeline_examples -v > logs/pipeline_examples/evaluation_logs.out 2>&1 | tee logs/pipeline_examples/evaluation_logs.out
      if: always()
    - name: Render goldenspike notebooks
      run: |
        mkdir -p logs
        python src/rail_notebooks/render_notebooks.py goldenspike -v pipeline_examples > logs/pipeline_examples/goldenspike_logs.out 2>&1 | tee logs/pipeline_examples/goldenspike_logs.out
      if: always()
      
    # Commit changes
    - uses: stefanzweifel/git-auto-commit-action@v7
      if: always()
      with: 
        commit_user_name: GitHub Actions Bot 
        commit_user_email: github-actions-bot@example.org
        commit_author: Author <actions@github.com>
